language : python

python:
  - 3.8      

install:
  - pip install requests
  - pip install openpyxl
  
script:
  - python3 app_test.py
  - python3 app_integracion_test.py
  - pytest app_test.py
  - pytest app_integracion_test.py